#!/usr/bin/env bash
# Installs Nginx with the following configurations

sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
