#!/usr/bin/env bash
# Installs Nginx with the following configurations

apt-get -y update
apt-get -y install nginx
sed -i "21s/^listen .*/listen 80" /etc/nginx/sites-enabled/defult
ufw allow 'Nginx HTTP'
echo Hello World > /var/www/html/index.nginx-debian.html
service nginx start
