#!/usr/bin/env bash
# Installs Nginx with the following configurations

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'
sudo ufw allow 22
sudo ufw --force enable

# nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart
