#!/usr/bin/env bash
# Configure server with: Nginx, custom 404, custom 301 redirect to google
# Add to HTTP header

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 22
sudo ufw --force enable
echo "Hello World!" | sudo tee /var/www/html/index.html

#permissions

sudo chmod -R 755 /var/www

#redirect

sudo sed -i '/^\tserver_name/a \\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}\n' /etc/nginx/sites-available/default

#page not found
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

sudo sed -i '/^\tserver_name/a \\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n' /etc/nginx/sites-available/default

sudo sed -i '/^\tserver_name/a \\n\tadd_header X-Served-By $HOSTNAME;\n' /etc/nginx/sites-available/default

#restart server
sudo service nginx restart
