#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend rehemamsosa.tech
        bind 0:80
        default_backend web_servers
backend web_servers
        balance roundrobin
        server 61131-web-01 100.25.36.243:80
        server 61131-web-02 52.3.249.197:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
