#!/usr/bin/env bash
# Installs HAProxy version 1.8

CFG= "\\\nlisten appname 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forward\n\tserver 61131-web-01 54.237.94.18 check\n
tserver 61131-web-02 54.209.89.175

sudo apt-get update
sudo apt-get -y install nginx
sudo apt-get install -y haproxy=1.5\*

# Make sure HAproxy can be managed via an init script
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy

# Backup original config file before attempt modifications
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Configure to include roundrobin and two servers
sudo sed -i "\$a $CFG" /etc/haproxy/haproxy.cfg

sudo service haproxy start
